# Generated by Django 4.2 on 2023-04-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ('name',), 'verbose_name': 'Dictionary', 'verbose_name_plural': 'Dictionaries'},
        ),
        migrations.AlterModelOptions(
            name='dictionarycategory',
            options={'ordering': ('name',), 'verbose_name': 'Dictionary Category', 'verbose_name_plural': 'Dictionary Categories'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ('name',), 'verbose_name': 'Term', 'verbose_name_plural': 'Terms'},
        ),
        migrations.AlterModelOptions(
            name='termcategory',
            options={'ordering': ('name',), 'verbose_name': 'Term Category', 'verbose_name_plural': 'Term Categories'},
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
