# Generated by Django 4.2 on 2023-04-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dictionary_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='is_start_term',
            new_name='is_star_term',
        ),
    ]
